language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.1'
  - '7.2'
  - nightly

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

services:
  - mysql
  - mongodb

before_install:
  - set -eo pipefail
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini || true
  - PHPUNIT_FLAGS='--stop-on-failure --verbose'
  - pecl install -f mongodb-stable

install:
    - composer self-update
    - composer config "platform.ext-mongo" "1.6.16"
    - composer install
    - rm -rf tests/Features/Functional/cache/*

before_script:
    - php console doctrine:database:create --env=test
    - php console doctrine:schema:create --env=test

script:
    - vendor/bin/behat

notifications:
    email: false
